version: "2"

services:
    runner:
        image: gitea/act_runner
        restart: always
        env_file: .env
        volumes:
            - ./data/act_runner:/data
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
            - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
